cohstats/coh2stats

- packages/web/src/App.tsx
- packages/web/src/components/main-header.tsx
- packages/web/src/pages/commanders/bulletinList.tsx
- packages/web/src/routes.ts
> Bulletinwork

- packages/web/src/pages/about/about.tsx
> Fix about sections

- packages/functions/src/libs/analysis/analysis.ts
- packages/functions/src/libs/analysis/composition.ts
- packages/functions/src/libs/analysis/match-analysis.ts
- packages/functions/src/libs/analysis/multi-day-analysis.ts
- packages/functions/src/libs/coh2-api.ts
- packages/functions/src/runTest.ts
- packages/functions/src/tests/analysis/composition.spec.ts
> Add BE functions for factions x faction analysis

- packages/web/src/pages/matches/match-details-table.tsx
- packages/web/src/pages/matches/tableStyle.css
Please use this branch if you want to merge.
> added sorting and result highlight on match detail table

- packages/web/src/pages/matches/match-details-table.tsx
- packages/web/src/pages/matches/tableStyle.css
- packages/web/src/pages/stats/custom-stats-general-data-provider.tsx
Fixed table header tooltips not clickable
> Match details sorting bugfix

- packages/web/src/App.tsx
As requested, the beta label was removed from the app.ts
If you find something wrong with this, please let me know instead of marking it as spam
And if you think the work was done as asked, please accept this PR and give it the hacktoberfest-accepted label
Thank you
> Remove beta label from the top site #79

- README.md
- packages/functions/src/libs/analysis/analysis-checker.ts
- packages/functions/src/libs/analysis/multi-day-analysis.ts
- Analysis is run everyday 
Fixes https://github.com/petrvecera/coh2ladders/issues/51
> #51 Run the analysis aggregation function every day

- packages/web/src/pages/matches/last-matches-table.tsx
close #78 
This pr adds download game data button to `last-matches-table.tsx`.
> Add download game data button

- packages/web/src/pages/bulletins/bulletinList.tsx
* This PR, adds a `search` query param to the URL for every time the search box text changes, and adds it to the browser's history.
* This is done by using the `useQuery` to grab a snapshot of the URL, and reading the current `search` query param if exists (otherwise assume empty), and executing an effect that filters the bulletins list using the read search query param, and set the search field (referenced by `useRef`) with the value read from the URL.
Fixes #120
> Add search query to the url of the bulletins list

- packages/app/src/renderer/components/team-view.tsx
- packages/app/src/renderer/windows/main/app.tsx
> Small UI improvements

- packages/app/src/main/applicationManager.ts
- packages/app/src/main/gameWatcher/parseLogFile.ts
- packages/app/src/renderer/windows/settings/app.tsx
- Fixed window positioning. Sometimes windows could be out of screen when screen layout changed
- Fixed new game found detection. If the exact same players played a second game the app thought it was the same game. https://github.com/petrvecera/coh2ladders/issues/162
- Improvement Added tooltips to settings. https://github.com/petrvecera/coh2ladders/issues/161
Notification sound is more complicated than anticipated since nodejs cant play sounds without external binary libaries. Need to have a look at this when I have more time https://github.com/petrvecera/coh2ladders/issues/161
> App fixes and improvements

- packages/app/package.json
- packages/app/src/main/index.ts
- packages/app/src/main/mixpanel.ts
- packages/app/src/typings/index.d.ts
Basically only a missing definition
> Mixpanel analytics improvements

- packages/app/src/main/applicationManager.ts
- packages/app/src/main/applicationStore.ts
- packages/app/src/redux/defaultState.ts
- packages/app/src/redux/slice.ts
- packages/app/src/redux/state.ts
- packages/app/src/renderer/utils/theme-dark.tsx
- packages/app/src/renderer/utils/theme-light.tsx
- packages/app/src/renderer/utils/theme-provider.tsx
- packages/app/src/renderer/windows/about/index.tsx
- packages/app/src/renderer/windows/main/index.tsx
- packages/app/src/renderer/windows/main/theme-provider.tsx
- packages/app/src/renderer/windows/preload.tsx
- packages/app/src/renderer/windows/settings/app.tsx
- packages/app/src/renderer/windows/settings/index.tsx
As long as we don't play modify colors on our own we might be OK with the default themes from Antd and theme switcher can always work
> Add dark theme

- packages/app/src/main/applicationManager.ts
https://github.com/petrvecera/coh2ladders/issues/179
> Fix maximize errors

- packages/app/src/main/applicationManager.ts
- packages/app/src/main/applicationWindow.ts
https://www.electronjs.org/docs/latest/api/app
https://stackoverflow.com/questions/52105917/electron-windows-app-close-not-ending-threads
> Fix quit of the app

- packages/app/src/main/applicationManager.ts
- packages/app/src/main/applicationStore.ts
- packages/app/src/main/applicationWindow.ts
- packages/app/src/main/mixpanel.ts
- packages/app/src/redux/slice.ts
- packages/app/src/redux/state.ts
Added close events for all windows with time 
Added open events for all windows
Added error event with applicationstate details and error message
Added quit event with application settings and runtime info
> App more events

- packages/functions/src/getPlayerCardEverythingHttp.ts
- packages/functions/src/getPlayerMatches.ts
- packages/functions/src/libs/coh2-api.ts
- packages/functions/src/libs/matches/matches.ts
- packages/functions/src/tests/coh2-api.spec.ts
This doesn't improve anything :(
> Batch the requests in match 

- packages/functions/src/searchPlayers.ts
- packages/web/src/pages/search/search.tsx
Fixes https://github.com/petrvecera/coh2ladders/issues/185
> Improve player search on the web 

- packages/app/src/main/index.ts
@petrvecera Maybe you have a better idea. Im out of ideas
> Remove install and uninstall events to fix installer

- packages/web/src/App.tsx
- packages/web/src/pages/live-matches/live-matches-card.tsx
- packages/web/src/pages/live-matches/live-matches-table.tsx
- packages/web/src/pages/live-matches/live-matches.tsx
- packages/web/src/pages/players/player-card.tsx
- packages/web/src/routes.ts
Fixes https://github.com/cohstats/coh2stats/issues/199
> Live matches improvements

- packages/web/src/components/main-home.tsx
- packages/web/src/pages/about/about.tsx
I keep getting this error
`TypeError: can't access property "analyzedMatches", t is null`
I try to figure out why and I see firebase is not loading do some issue with my country.
Also some extensions block firebase for tracking.
So I add a check before accessing analyzedMatches.
> Sometime data["analyzedMatches"] is null

- packages/web/src/pages/live-matches/live-matches-table.tsx
- packages/web/src/pages/players/player-card.tsx
Fixes https://github.com/cohstats/coh2stats/issues/222
> Fix the player cards replace of name

- packages/web/src/pages/match/single-match.tsx
I added the expiration notes and a tooltip as mentioned. 
please tell me if you need any more changes. 
Thanks :)
> added expiration note ( issue #253 )

- packages/web/src/pages/matches/match-details.tsx
Display empty card when no data are received  [Fixes #260]
> Fix : Display empty card when no data are received. fixes #260

- .github/workflows/electron-build-release.yaml
- .github/workflows/electron-build.yaml
- packages/web/src/pages/search/search.tsx
I've done with my contribution to the search
As discussed in Issue #258 I am using the existing functions of the search commander and search Bulletins mentioned there.
https://user-images.githubusercontent.com/8092680/194460941-879bbecb-af94-4526-a08c-291badb6afb7.mp4
Let me know if there are some changes to make to my code
> Implementation of search page

- packages/web/src/pages/desktop-app/desktop-app.tsx
> Adds Downloads count

- packages/web/src/components/main-header.tsx
> Update the top menu to the new AntD version

- packages/web/src/App.tsx
- packages/web/src/pages/not-found/index.ts
- packages/web/src/pages/not-found/not-found.tsx
Adds 404 page based off of antd's 404 Result demo.
Fixes #272 
**Screenshot**
> Add 404 page

- packages/web/src/pages/live-matches/live-matches-table.tsx
This fix remove link to pagination with no data
> Fix pagination in live games table

- packages/web/package.json
- packages/web/src/App.tsx
- packages/web/src/components/alert-box-china.tsx
- packages/web/src/pages/stats/old-stats.tsx
- packages/web/src/root.tsx
- yarn.lock
Mostly okay, expect for one segment in root.tsx:
```
<Route path="/">
<ConfigsProvider configJson={{}}>
<App />
</ConfigsProvider>
</Route>
```
No able to convert this to CompatRoute, likely due to the CompactRouter component being inside the App component. Tried moving CompactRouter to the root.tsx but causes issues with the navigation.
> First Implementation with react-router-dom-v5-compat

- packages/app/package.json
- yarn.lock
Reverts cohstats/coh2stats#335
> Revert "Update dependency @vercel/webpack-asset-relocator-loader to v1.7.4"

- .github/workflows/deploy-preview.yaml
Add a new GitHub Actions workflow to deploy to Firebase hosting preview environment on PR.
* Create a new workflow file `.github/workflows/deploy-preview.yaml`.
* Set the workflow to trigger on pull requests.
* Use the Firebase hosting deploy action to deploy to the preview environment.
* Configure the PR environment to live for 7 days using the `expires` parameter.
* Update the `uses` action to the correct versions.
* Utilize `yarn` instead of `npm` for installing dependencies and building the project.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/cohstats/coh2stats/pull/371?shareId=bb43dc0c-537b-4a7a-8e8a-68629c3fabed).
> Add Firebase hosting preview environment for PRs
